"use client";

import { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { Header } from "@/components/Header";
import { ThemeProvider } from "next-themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header />
          <div className="min-h-screen w-full mx-auto justify-between transition-all duration-500 px-4 bg-gray-50 dark:bg-gray-900 sm:px-6 lg:px-8 lg:flex lg:flex-row">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
